// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/blocked.html"
    | "/content-scripts/anti-adblock.js"
    | "/content-scripts/content.js"
    | "/content-scripts/dark-inject.js"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/icon.svg"
    | "/options.html"
    | "/popup.html"
    | "/rules/adblock.json"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
